---
- name: Install miniDNLA
  apt:
    name: minidlna
    state: present

- name: Ensure that configured cache dir exists
  file:
    path: "{{ minidlna.db_dir | default('var/cache/minidlna') }}"
    state: directory
    owner: "{{ minidlna.user | default('minidlna') }}"
    group: "{{ minidlna.group | default('minidlna') }}"
    mode: 0755

- name: Copy miniDLNA configuration in place.
  template:
    src: minidlna.conf.j2
    dest: /etc/minidlna.conf
    owner: root
    group: root
    mode: 0644

- name: Copy default configuration
  template:
    src: minidlna.default.j2
    dest: /etc/default/minidlna
    owner: root
    group: root
    mode: 0644

- name: Ensure miniDLNA is enabled to start at boot.
  service:
    name: minidlna
    enabled: yes

- name: Ensure miniDLNA is restarted.
  service:
    name: minidlna
    state: restarted
  failed_when: not (minidlna_ignore_restart_error | bool | default(no))
